# Way Back Home - Cloud Build Configuration
# Builds and deploys backend API and frontend to Cloud Run
#
# Prerequisites:
#   - Firebase must be enabled for the project
#   - Artifact Registry repository must exist (run setup-infrastructure.sh)
#
# Usage:
#   gcloud builds submit --config cloudbuild.yaml
#
# Deploy only backend:
#   gcloud builds submit --config cloudbuild.yaml --substitutions=_DEPLOY_FRONTEND=false
#
# Deploy only frontend:
#   gcloud builds submit --config cloudbuild.yaml --substitutions=_DEPLOY_BACKEND=false
#
# With custom domains:
#   gcloud builds submit --config cloudbuild.yaml \
#     --substitutions=_API_BASE_URL=https://api.example.com,_MAP_BASE_URL=https://example.com

substitutions:
  _REGION: us-central1
  _AR_REPO: way-back-home
  # Service names
  _API_SERVICE_NAME: way-back-home-api
  _FRONTEND_SERVICE_NAME: way-back-home-frontend
  # Default URLs - override with --substitutions for custom domains
  _API_BASE_URL: https://api.waybackhome.dev
  _MAP_BASE_URL: https://waybackhome.dev
  # Deploy flags (set to 'false' to skip)
  _DEPLOY_BACKEND: 'true'
  _DEPLOY_FRONTEND: 'true'

steps:
  # =============================================================================
  # BACKEND BUILD & DEPLOY
  # =============================================================================

  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_BACKEND}" = "true" ]; then
          docker build \
            -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_API_SERVICE_NAME}:${BUILD_ID} \
            -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_API_SERVICE_NAME}:latest \
            ./backend
        else
          echo "Skipping backend build"
        fi
    id: 'build-backend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_BACKEND}" = "true" ]; then
          docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_API_SERVICE_NAME}:${BUILD_ID}
          docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_API_SERVICE_NAME}:latest
        else
          echo "Skipping backend push"
        fi
    id: 'push-backend'
    waitFor: ['build-backend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_BACKEND}" = "true" ]; then
          gcloud run deploy ${_API_SERVICE_NAME} \
            --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_API_SERVICE_NAME}:${BUILD_ID} \
            --region ${_REGION} \
            --platform managed \
            --allow-unauthenticated \
            --service-account firebase-adminsdk-fbsvc@${PROJECT_ID}.iam.gserviceaccount.com \
            --set-env-vars "GOOGLE_CLOUD_PROJECT=${PROJECT_ID},FIREBASE_STORAGE_BUCKET=${PROJECT_ID}.firebasestorage.app,API_BASE_URL=${_API_BASE_URL},MAP_BASE_URL=${_MAP_BASE_URL}" \
            --memory 2Gi \
            --cpu 2 \
            --min-instances 0 \
            --max-instances 10 \
            --concurrency 80 \
            --timeout 60s
        else
          echo "Skipping backend deploy"
        fi
    id: 'deploy-backend'
    waitFor: ['push-backend']

  # =============================================================================
  # FRONTEND BUILD & DEPLOY
  # =============================================================================

  # Build frontend Docker image
  # Note: NEXT_PUBLIC_* vars must be set at build time
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_FRONTEND}" = "true" ]; then
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=${_API_BASE_URL} \
            --build-arg NEXT_PUBLIC_FRONTEND_URL=${_MAP_BASE_URL} \
            -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_FRONTEND_SERVICE_NAME}:${BUILD_ID} \
            -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_FRONTEND_SERVICE_NAME}:latest \
            ./frontend
        else
          echo "Skipping frontend build"
        fi
    id: 'build-frontend'

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_FRONTEND}" = "true" ]; then
          docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_FRONTEND_SERVICE_NAME}:${BUILD_ID}
          docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_FRONTEND_SERVICE_NAME}:latest
        else
          echo "Skipping frontend push"
        fi
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${_DEPLOY_FRONTEND}" = "true" ]; then
          gcloud run deploy ${_FRONTEND_SERVICE_NAME} \
            --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_FRONTEND_SERVICE_NAME}:${BUILD_ID} \
            --region ${_REGION} \
            --platform managed \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 20 \
            --concurrency 100 \
            --timeout 60s
        else
          echo "Skipping frontend deploy"
        fi
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1200s'